# Generated by Django 4.2.1 on 2023-05-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='carousel',
        ),
        migrations.DeleteModel(
            name='ImagenCarousel',
        ),
    ]
