# Generated by Django 4.2.1 on 2023-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Empleado'), ('3', 'Recursos Humanos')], default='2', max_length=2, verbose_name='Rol'),
        ),
    ]
